source 'http://rubygems.org'

gem 'rails'
gem 'sqlite3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

gem 'jquery-rails'
gem 'bcrypt-ruby'

gem 'rspec-rails', :group => [:test, :development]
group :test do
  gem 'capybara'
  gem 'factory_girl_rails'
end
